// Package ports provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ports

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HashtagSyncResponse defines model for HashtagSyncResponse.
type HashtagSyncResponse struct {
	Status *string             `json:"status,omitempty"`
	SyncAt *openapi_types.Date `json:"sync_at,omitempty"`
}
